### ISSUE TITLE
Bend and Stretched Polled Failed

### ISSUE THREAD

**Issue by DhruvKoolRajamani** [bendlabs/one_axis_ads#2]
Tried running the bend and stretch polled example but the arduino ran out of memory while flashiing the firmware. Ported the library to mbed and used an nxp lpc1768 to communicate with the sensor. Succesfully got Bend values in polled mode. Tried flashing the firmware using the mbed library but now I can't find the sensor address on the i2c bus. Tried different i2c debugging steps but to no avail. Does the stretch work with newer versions of the sensor (if I buy it now) and can somebody help me recover my sensor?

**Comment by SShattered** [comment]
> Tried running the bend and stretch polled example but the arduino ran out of memory while flashiing the firmware. Ported the library to mbed and used an nxp lpc1768 to communicate with the sensor. Succesfully got Bend values in polled mode. Tried flashing the firmware using the mbed library but now I can't find the sensor address on the i2c bus. Tried different i2c debugging steps but to no avail. Does the stretch work with newer versions of the sensor (if I buy it now) and can somebody help me recover my sensor?

How did you resolve this?

**Comment by DhruvKoolRajamani** [comment]
I think I sent it back to them and they upgraded the version and sent it back to me. (I'm not sure, it's been a while since I last used this sensor).

**Comment by SShattered** [comment]
> I think I sent it back to them and they upgraded the version and sent it back to me. (I'm not sure, it's been a while since I last used this sensor).

Thanks! I got it working.

**Comment by jendy12345** [comment]
Hello, how do you solve the problem that the I2C address was originally detected but suddenly it cannot be detected? Because I have also encountered this problem, but I can't find a solution so far.Can you please tell me?
