### ISSUE TITLE
Can I connect multiple one-axis-ads sensors to ESP32? And how I can do that?

### ISSUE THREAD

**Issue by Korzhak** [bendlabs/one_axis_ads#3]
Hello. I bought 24 one-axis-ads sensors, and I need to connect 5 flex-sensors to a ESP32. 
How can I do this? And do I need a I2C multiplexer for this?

**Comment by coltonottley** [comment]
Yeah the quickest way to connect multiple sensors to one bus using the
ESP32 is the Sparkfun library found here
https://github.com/sparkfun/SparkFun_Displacement_Sensor_Arduino_Library

**Comment by Korzhak** [comment]
Thank you very much! It works!
